[package]
name = "simpledb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "simpledb"
path = "src/main.rs"

[[bin]]
name = "filetest"
path = "src/filetest.rs"